(function(){'use strict';
var DEFAULT_SOURCE='/data/trade-shows.json',DEFAULT_LIMIT=8,cache={};
function t(k,f){return window.__BARTENDLY_I18N__&&window.__BARTENDLY_I18N__.flat&&window.__BARTENDLY_I18N__.flat[k]?window.__BARTENDLY_I18N__.flat[k]:f;}
function l(){var h=(document.documentElement.getAttribute('lang')||'').trim(),s=document.querySelector('[data-language-select]');return (h||(s&&s.value)||'en').split('-')[0];}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
function date(v){if(!v||typeof v!=='string'){return null;}var p=v.slice(0,10).split('-'),y=+p[0],m=+p[1]-1,d=+p[2];if(p.length!==3||!y||m<0||m>11||!d||d<1||d>31){return null;}return new Date(y,m,d);}
function today(){var n=new Date();return new Date(n.getFullYear(),n.getMonth(),n.getDate());}
function norm(e){if(!e||!e.name||!e.startDate){return null;}var s=date(e.startDate),en=date(e.endDate||e.startDate);if(!s||!en){return null;}return{name:String(e.name),venue:e.venue?String(e.venue):'',startDate:e.startDate,endDate:e.endDate||e.startDate,url:e.url?String(e.url):'',city:e.city?String(e.city).toLowerCase():'',start:s,end:en};}
function events(data,city){city=String(city||'').toLowerCase();if(Array.isArray(data)){return data.filter(function(e){return !e.city||String(e.city).toLowerCase()===city;});}if(data&&Array.isArray(data[city])){return data[city];}if(data&&data.cities&&Array.isArray(data.cities[city])){return data.cities[city];}if(data&&data.tradeShows&&Array.isArray(data.tradeShows[city])){return data.tradeShows[city];}if(data&&Array.isArray(data.events)){return data.events.filter(function(e){return !e.city||String(e.city).toLowerCase()===city;});}return [];}
function formatRange(e,lang){var s=e.start,en=e.end,same=s.getTime()===en.getTime(),sameMonth=s.getFullYear()===en.getFullYear()&&s.getMonth()===en.getMonth(),sameYear=s.getFullYear()===en.getFullYear(),day=new Intl.DateTimeFormat(lang,{day:'numeric'}),monthYear=new Intl.DateTimeFormat(lang,{month:'long',year:'numeric'}),dayMonth=new Intl.DateTimeFormat(lang,{day:'numeric',month:'long'}),full=new Intl.DateTimeFormat(lang,{day:'numeric',month:'long',year:'numeric'});if(same){return full.format(s);}if(sameMonth){return day.format(s)+'–'+day.format(en)+' '+monthYear.format(en);}if(sameYear){return dayMonth.format(s)+' – '+full.format(en);}return full.format(s)+' – '+full.format(en);}
function card(e,lang){var label=t('experiences.tradeShows.externalLink','Event site'),meta=formatRange(e,lang)+(e.venue?' · '+e.venue:''),link=e.url?'<a class="trade-show-card__link" href="'+esc(e.url)+'" target="_blank" rel="noopener noreferrer">'+esc(label)+'</a>':'';return'<article class="trade-show-card"><div class="trade-show-card__main"><h3 class="trade-show-card__name">'+esc(e.name)+'</h3><p class="trade-show-card__meta">'+esc(meta)+'</p></div>'+link+'</article>';}
async function load(src){if(cache[src]){return cache[src];}var r=await fetch(src,{headers:{'Accept':'application/json'},cache:'no-store'});if(!r.ok){throw new Error(src+' returned '+r.status);}var d=await r.json();cache[src]=d;return d;}
function msg(el,key,f){el.innerHTML='<p class="trade-show-empty">'+esc(t(key,f))+'</p>';}
async function render(el){var city=el.getAttribute('data-trade-shows-city');if(!city){return;}var src=el.getAttribute('data-trade-shows-source')||DEFAULT_SOURCE,limit=parseInt(el.getAttribute('data-trade-shows-limit')||DEFAULT_LIMIT,10);if(!isFinite(limit)||limit<=0){limit=DEFAULT_LIMIT;}el.setAttribute('aria-busy','true');el.innerHTML='<p class="trade-show-empty">'+esc(t('experiences.tradeShows.loading','Loading upcoming fairs…'))+'</p>';try{var data=await load(src),lang=l(),list=events(data,city).map(norm).filter(Boolean).filter(function(e){return e.end>=today();}).sort(function(a,b){return a.start-b.start||a.name.localeCompare(b.name);}).slice(0,limit);if(!list.length){msg(el,'experiences.tradeShows.empty','No upcoming trade shows are listed yet.');return;}el.innerHTML=list.map(function(e){return card(e,lang);}).join('');}catch(err){console.warn('[Bartendly trade shows]',err);msg(el,'experiences.tradeShows.error','Upcoming fairs could not be loaded right now.');}finally{el.setAttribute('aria-busy','false');}}
function renderAll(){document.querySelectorAll('[data-trade-shows-city]').forEach(function(el){render(el);});}
function boot(){renderAll();}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',boot);}else{boot();}
document.addEventListener('bartendly:i18n-ready',boot);document.addEventListener('bartendly:language-changed',boot);window.BartendlyTradeShows={render:renderAll};
})();